### ISSUE TITLE
VFR 1200F

### ISSUE THREAD

**Issue by sabsteef** [MCU-Innovations/HondaECU#25]
Hi,

i go an VFR 1200. and want to read and write the Firmware.
But when i try to read the firmware. it gives me the error "Password failed"
if i use the HondaFlasher every this is working. i can read the complete Firmware.
do i need to change the password somewhere?

**Comment by sabsteef** [comment]
nevermind the beta version does not gave the issue. and works like a charm. so its fixed. tnx
Kudos. Maybe i can help to make it complete compatible with a VFR 1200?

**Comment by edwinopie** [comment]
Where to get the beta version?
