### ISSUE TITLE
ADD VFR1200 ecm id

### ISSUE THREAD

**Issue by sabsteef** [MCU-Innovations/HondaECU#26]
Never mind

**Comment by RyanHope** [comment]
Can you tell me what the ECMID is for the VFR1200?

**Comment by sabsteef** [comment]
Hi, i think it's 


	b"\x01\x00\xaa\x01\x02": {"model":"VFR1200F","year":"2010-2011","pn":"38770-MGE-D02","checksum":"0x7FFF8","ecmidaddr":"0x7FF5C","region":"EUROPE"}, 

but im blind for  the keihinaddr
