### ISSUE TITLE
HondaEcu connection problem

### ISSUE THREAD

**Issue by MotoRopi85** [MCU-Innovations/HondaECU#27]
there is a user manual for the proper operation of the program?
the connection cable in the list does not appear while "HondaECU" works on my computer normally

whatever help is important to me!

**Comment by JabaRacing** [comment]
Hello
For Windows
HondaECU for Windows requires the libusbK driver. Download Zadig ( https://zadig.akeo.ie/ ) and use it to install the libusbK driver. There is a usage guide on the Zadig website if you need help using it. Once libusbK is installed for your FTDI device, download the latest release of HondaECU.exe.
The hardware works very well to me
