### ISSUE TITLE
CBR 600rr 38770 mee 643

### ISSUE THREAD

**Issue by vasiliouv84** [MCU-Innovations/HondaECU#30]
I have this ECU but I can't work with your program.no live data no nothing.please update your program of you can.
what do you want from me to do?

**Comment by vasiliouv84** [comment]
can you update the program for the CBR 600rr 2004 model and add any xdf of this model?

**Comment by vasiliouv84** [comment]
cbr 600rr 2004 ecu bin file
[38770-MEE-643.zip](https://github.com/MCU-Innovations/HondaECU/files/3333487/38770-MEE-643.zip)

**Comment by vasiliouv84** [comment]
I can't connect my ECU with your program.what I am doing wrong?

**Comment by RyanHope** [comment]
What cable are you using?

**Comment by vasiliouv84** [comment]
a vag com with ftdi ft232rl chip.it is the same cable that I use to extract
my ECU bin with honda ECU flasher a tool from an Italian guy.

**Comment by vasiliouv84** [comment]
> What cable are you using?

any ideas what to do??

**Comment by vasiliouv84** [comment]
I believe that you have to add the ECU Id at your program to work.if there is anything that I can do please tell me.

**Comment by JabaRacing** [comment]
first you need to install libusbk for windows
after running the program going to file> devices it will show your cable as
a device option, if this is not happening it will not be possible to
communicate

Em seg, 1 de jul de 2019 às 17:10, vasiliouv84 <notifications@github.com>
escreveu:

**Comment by vasiliouv84** [comment]
I have done this things but nothing.

**Comment by CBRTricolor** [comment]
I’ve the same problem ☹
 

  <https://t.xink.io/Tracking/Impression/eiUAAIW_AADy7zwA0> 

De: vasiliouv84 <notifications@github.com> 
Enviada: 2 de julho de 2019 18:55
Para: MCU-Innovations/HondaECU <HondaECU@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Assunto: Re: [MCU-Innovations/HondaECU] CBR 600rr 38770 mee 643 (#30)

 

I have done this things but nothing.

**Comment by RyanHope** [comment]
Adding the ECU id has nothing to do with this.

**Comment by vasiliouv84** [comment]
but as I have seen the ECU Id isn't at your program.if you add it maybe it will work.if not what else can we do to help?

**Comment by vasiliouv84** [comment]
with the newest beta version I was able to connect to my ECU but the ECU state was going from on to unknown state.i was able to use the logger but I was unable to read or write the ECU of my bike.

**Comment by bikedyno** [comment]
Hi
Do You the xdf defination for this ECU,
Turnerpro RT

THANKS
Pete
