### ISSUE TITLE
Honda Small bike ecu compatibilty?

### ISSUE THREAD

**Issue by edwinopie** [MCU-Innovations/HondaECU#38]
hi,
can i use HOndaecu to read this ecus:

38770-K25-901 BeAT FI, BeAT FI CBS, Scoopy FI, Scoopy eSP
38770-K45-N42 New CBR 150R K45G
38770-K46-N01 Scoopy eSP (New) & Vario 110 eSP
38770-K15-902 CB150R StreetFire (Old)
38770-K18-902 Verza 150 FI
38770-K41-N01 Blade FI & Supra X 125 FI
38770-K15-921 New CB150R Streetfire K15G
38770-K84-901 CRF150
38770-K45-N01 CBR150R 2014-2016

30400-K25-600C1 BeAT POP eSP & Scoopy eSP
30400-K60-B11 Vario 125 eSP (B11)
30400-K59-A01 Vario 150 eSP
30400-K46-N31 New Vario 110 FI eSP
30400-K81-N62 Beat ESP
30400-K59-A71 New Vario 150 K59J

i tried to connect, success. datalog working, but when i try to read it show paswword failed.

any suggestion?

**Comment by yvan746** [comment]
Hi ,
I have the same problem.
Which tool you use (FTDI or build Ryan tool?)?

**Comment by edwinopie** [comment]
I use ftdi 232rl.. its a vagcom usb kkl..

**Comment by edwinopie** [comment]
Which tool you are using? Can you show me?

**Comment by bikedyno** [comment]
Hi
Do You the xdf defination for this ECU,
Turnerpro RT

THANKS
Pete

**Comment by edwinopie** [comment]
No i dont, I am not using Tunerpro.

**Comment by yvan746** [comment]
I have the same problem with FTDI 232RL vagcom then I will try with Ryan tool and I will see

**Comment by clevim23** [comment]
tente a senha FF FF FF FF FF FF FF FF FF FF FF FF FF FF

**Comment by RyanHope** [comment]
@edwinopie do you still have access to all the bikes you listed in your op? would it be possible for you to get me the ecmid of each of them so I can update HondaECU

**Comment by edwinopie** [comment]
Yes i can. Asap thank yoi..

**Comment by yvan746** [comment]
@edwinopie Did you resolve the problem with KKL usb interface?

**Comment by makunetsumaru** [comment]
@RyanHope i got same issue as edwinopie.
38770-K45-N42 New CBR 150R K45G (ECM ID: 01 02 04 0f 01)

**Comment by RyanHope** [comment]
Need more details about your setup.

**Comment by makunetsumaru** [comment]
what kind of detail do you need that can help you?

Pada tanggal Rab, 31 Jul 2019 pukul 18.22 Ryan Hope <
notifications@github.com> menulis:

**Comment by RyanHope** [comment]
@makunetsumaru sorry, the details question was a mistake I thought this was a different issue, if you are getting a password failed error then the ecu needs to get backdoord so we can learn what the password is.

**Comment by edwinopie** [comment]
Noted
