### ISSUE TITLE
Checksum problems and incompatibilities. After editing via tunerpro rt

### ISSUE THREAD

**Issue by GeorgeTurbo** [MCU-Innovations/HondaECU#42]
Hello. I encountered a problem when editing the bin file extracted from ecu ori. Corrected via tunerpro. But when the flash entered the car. The car could not start. I found that due to checksum problems That does not match. How should I fix it?

**Comment by RyanHope** [comment]
Check the fix checksum box in the flash dialog and then enter the checksum location in the field.

**Comment by GeorgeTurbo** [comment]
I'm still a beginner. Do you have a picture? Thank You
