### ISSUE TITLE
CBR300 ecu, Eculib file with pycharm doesnt found.

### ISSUE THREAD

**Issue by Josileissu** [MCU-Innovations/HondaECU#47]
Hi,

I'm using PyCharm to test this code for remap my motorcycle. Can you help me step by step to use your code?

I have access to cbr's on my brothers office and i wanna help he to adjust injection...

Att,

**Comment by RyanHope** [comment]
Eculib is in another one of my repos so that I can use the code in other
projects.

**Comment by Josileissu** [comment]
Oh, sorry.

I see that exist an exe file. So what i need to remap my motorcicle (cause im adjusting my cbf 250 with pgmfi from cb300r), is use your HondaEcu.exe to extract bin file from ecu? After this i use turnerpro to do modifications and write again use HondaEcu in the ECU ?

Sorry for my english, i'm lazzy to use translate ¬¬ haha.

thx

**Comment by RyanHope** [comment]
You will need an xdf for the cb300 before you can do anything in TunerPro
but you have the general process down.

**Comment by Josileissu** [comment]
Sorry for the inconvenience.

1° - Can i obtain an xdf file from the motorcycle?
2° - How to do this?
3° - Where is the general process?
4° - The wiring diagram that we need to do, the 4N25 optocouplers, resistors and led... U has an image from this device?
5° - Do you know the pgmfi works flex fuel, i will take an problem with this using tunerpro?

I'm not a eletrical engineering, and not a technicall, but i understand quickly if u help me :)

Thx

**Comment by Josileissu** [comment]
FTDI is this device? That i need to to this wiring adjust for use to receive the files?
![image](https://user-images.githubusercontent.com/53374605/62429825-ebba4880-b6e9-11e9-821a-265e174ccdad.png)

Wiring adjust.
![image](https://user-images.githubusercontent.com/53374605/62429829-0bea0780-b6ea-11e9-8aee-0c74daadc13e.png)

Pc serial port is that sector in the begin on pcb?

**Comment by Josileissu** [comment]
or is this?
![image](https://user-images.githubusercontent.com/53374605/62429957-ac412b80-b6ec-11e9-8a48-9842cc9961df.png)

**Comment by RyanHope** [comment]
Both will probably work

**Comment by Josileissu** [comment]
Can u send an image that device you use? For i see? Then i copy you :)

**Comment by Josileissu** [comment]
I'm searching in the net, i found this device.
So you use that i show first.
![image](https://user-images.githubusercontent.com/53374605/62430292-f1fff300-b6f0-11e9-94df-ef82d02c3d1e.png)

https://gonzos.net/projects/ctx-obd/
