### ISSUE TITLE
Honda sonic 150 38770 k56 n01

### ISSUE THREAD

**Issue by cuongbo280599** [MCU-Innovations/HondaECU#48]
1. Do u have bin, xdf file of ecu sonic 150r?
2. Where i take password my ecu
3. Do u manual everyone define xdf on tuner pro, please

**Comment by RyanHope** [comment]
All the bins that I have for Hondas are on in the repo

**Comment by cuongbo280599** [comment]
Ok, tks you hehe

Do u manual make define xdf on tunerpro?

**Comment by cuongbo280599** [comment]
I wish u have group for honda ecu on facebook

**Comment by Bud1man** [comment]
i have that genuine bin and xdf you mentioned, mail me

**Comment by cuongbo280599** [comment]
Oki tks you before
Mail me kunmin2805@gmail

**Comment by cuongbo280599** [comment]
I sent mail to you. Tks

**Comment by RyanHope** [comment]
See #61
