### ISSUE TITLE
Read FTDI

### ISSUE THREAD

**Issue by Josileissu** [MCU-Innovations/HondaECU#49]
Hi,

How can i read the ftdi conversor direct from the pc to obd port?

I try use TTL but i cant do this. 

OBD Port - CB300
![WhatsApp Image 2019-08-06 at 09 20 06](https://user-images.githubusercontent.com/53374605/62539510-b7e73c00-b82b-11e9-8486-9dead5fb356f.jpeg)

I'm using protoboard to test the ryan circuit to separate obd from ftdi
![WhatsApp Image 2019-08-06 at 09 20 06 (1)](https://user-images.githubusercontent.com/53374605/62539522-bf0e4a00-b82b-11e9-9e41-8b579ed4552a.jpeg)

![WhatsApp Image 2019-08-06 at 09 20 06 (2)](https://user-images.githubusercontent.com/53374605/62539564-d6e5ce00-b82b-11e9-9251-15f4aaecc6ad.jpeg)

I bought the ftdi with ft232 but i cant read this from my computer. How can i do this? What i need?
Need usb 2.0? I cant plug into a 3.0?

**Comment by Josileissu** [comment]
i've tried to use ttl with hondaecu.exe but i know this dont work cause the .exe needs ftdi.

**Comment by TrustyTristan** [comment]
Your breadboard looks wrong. The Optocoupler's look like they are on the same connected to the same tracks.

See this
![alt text](https://user-images.githubusercontent.com/17605686/60763646-31b8c800-a0bc-11e9-9b90-adb2fac2247e.jpg)

**Comment by Josileissu** [comment]
Oh, thanks. My brother helps me to connect on to breadboard.

I've try to connect FT232RL on my computer and i got it. Just use the correct usb cable will appear in com serial. After installing libusbk they will appear in a new item in device manager. And after this, is ok to connect with HondaEcu.exe

So the next step i need to do is to connect with my cb300 to get parameters. haha' Discovering a new world :O

**Comment by Josileissu** [comment]
Here is the breadboard mounted, thx for helping. I show for my another brother (hahaha, here we ate in 7 brothers), and he helps me to adjust.

![IMG_20190806_221337](https://user-images.githubusercontent.com/53374605/62587455-7771d780-b898-11e9-8707-2c4c67ee8780.jpg)
![IMG_20190806_221350](https://user-images.githubusercontent.com/53374605/62587456-7771d780-b898-11e9-8125-74c70db9b059.jpg)
![IMG_20190806_221321](https://user-images.githubusercontent.com/53374605/62587458-7771d780-b898-11e9-89b9-b4429ebeab01.jpg)
![IMG_20190806_221326](https://user-images.githubusercontent.com/53374605/62587460-780a6e00-b898-11e9-9a66-fe0bf7603217.jpg)
![IMG-20190806-WA0019](https://user-images.githubusercontent.com/53374605/62587461-780a6e00-b898-11e9-9e9d-317260745bd5.jpeg)
![IMG_20190806_221317](https://user-images.githubusercontent.com/53374605/62587462-78a30480-b898-11e9-9656-5ca188022e9f.jpg)

**Comment by Josileissu** [comment]
Here, i cant read. Wat im doing wrong?

![IMG_20190807_195555](https://user-images.githubusercontent.com/53374605/62663561-61bee980-b94e-11e9-84c7-6dcc5e518a5d.jpg)
![IMG_20190807_195542](https://user-images.githubusercontent.com/53374605/62663568-67b4ca80-b94e-11e9-9c32-fe9777b724cb.jpg)
![15652190047698974050748696601997](https://user-images.githubusercontent.com/53374605/62663572-6edbd880-b94e-11e9-8632-55b1782d9629.jpg)

**Comment by Josileissu** [comment]
Ok, i ger an unknow bike
![IMG_20190807_201144](https://user-images.githubusercontent.com/53374605/62664054-6edcd800-b950-11e9-8e5b-752e23f3acdf.jpg)
![Uploading IMG_20190807_201151.jpg…]()

**Comment by Josileissu** [comment]
I created an file call cb300.bin without text.
And put in the file field.
Is this method correct?

![IMG_20190807_202323](https://user-images.githubusercontent.com/53374605/62664284-6638d180-b951-11e9-9d89-d7be2f8b3628.jpg)

**Comment by RyanHope** [comment]
What is the ECU part number and other model info and I can update the code

**Comment by Josileissu** [comment]
The model of motorcycle is: CB300R 2015
Keihin ECU: 38770-KVK-B23
Flex fuel

**Comment by Josileissu** [comment]
here, i take a picture from the ecu. My brother almost burst the connector hahaha. Join the 12v with gnd oO"
![IMG_20190807_204052_1](https://user-images.githubusercontent.com/53374605/62664920-c466b400-b953-11e9-9092-daed9a4808de.jpg)

**Comment by RyanHope** [comment]
Thanks I will add this info to the next release.

**Comment by Josileissu** [comment]
I thank you that. Is this release are include this ecu, 3.1.5?

**Comment by prostreetprotege** [comment]
Hey Ryan. Can you add my ecmid on next release

38770-MJW-T11

Thankyou so much

**Comment by vasiliouv84** [comment]
Hello Ryan can you add ecmid 38770 mee 643?
Thanks in advance

**Comment by Josileissu** [comment]
Hi, i've trying to use in pycharm your code to test... And i have an doubt, what will happen after i connect the diagnostic port from motorcycle to my pc using you software?

Regards.

![image](https://user-images.githubusercontent.com/53374605/62744838-d06b7800-ba1e-11e9-838a-d4adc6392b70.png)

**Comment by clevim23** [comment]
![IMG_20190809_192030](https://user-images.githubusercontent.com/47676317/62812268-5c42da00-badb-11e9-997d-9ccabaa33ee7.jpg)

**Comment by clevim23** [comment]
Hello I have this error when trying to read the ECU XRE 300 12

**Comment by clevim23** [comment]
[log.txt](https://github.com/MCU-Innovations/HondaECU/files/3488199/log.txt)

**Comment by Josileissu** [comment]
Hi,

I connected with the last release but the log file doesnt stop
![image](https://user-images.githubusercontent.com/53374605/62816380-a8524680-bafc-11e9-9df4-2b76278e61ae.png)

What i'm doing wrong?
[logcb300.txt](https://github.com/MCU-Innovations/HondaECU/files/3488427/logcb300.txt)

**Comment by RyanHope** [comment]
Doesn't look like anything is wrong.

**Comment by Josileissu** [comment]
What i need to do? I just put the ftdi on the connectors and wait? Doesnt need insert bin file in the field for this?

**Comment by Josileissu** [comment]
Here i tested running, but only o2 sensor goes.

**Comment by Josileissu** [comment]
![15654411735814956411260674849539](https://user-images.githubusercontent.com/53374605/62821988-b67f8180-bb53-11e9-9b24-c9685da0d7ab.jpg)

**Comment by edwinopie** [comment]
Hi ryan,
Can you add 38770-K84-901 on next Hondaecu release? I got unknown model too..

**Comment by RyanHope** [comment]
What is the ecmid and model info?

**Comment by edwinopie** [comment]
Model : CRF150L 
ECM ID: 01 02 32 0f 01

**Comment by RyanHope** [comment]
@Josileissu  what do you mean "only o2 sensor goes"?

**Comment by RyanHope** [comment]
@edwinopie added the info with commit 22e423a4d4fa812216f2e0bf7c2d5c89e210d34f, can you send me the bin for this bike as well so I can update the collection?

**Comment by edwinopie** [comment]
I can. I was using other flasher, But i am not sure it was the right reading address.. or let.say the right bin size file..

**Comment by RyanHope** [comment]
If you can email me all the read attempts you have done I can check things
over.

**Comment by edwinopie** [comment]
done, emailed to you
