### ISSUE TITLE
Please help Can't Flash to Bike

### ISSUE THREAD

**Issue by prostreetprotege** [MCU-Innovations/HondaECU#50]
i'm doing XDF for cb650f2018 finish
and Flash to bike.    Result/Good
But i can't start the bike
And Now i'm can't flash the original file to bike

Please help

**Comment by prostreetprotege** [comment]
![image](https://user-images.githubusercontent.com/53036434/62838884-4a646100-bcac-11e9-8ebd-612f4378ce4b.png)

can't connect to ecu

**Comment by RyanHope** [comment]
Where did you get this 650 xdf from? Is it correct? Did you just soft brick
your ecu flashing a bad bin?

**Comment by prostreetprotege** [comment]
i'm write this xdf by self
Do you have softbrick solution ?

**Comment by RyanHope** [comment]
Yeah there is a post on my FB page on how to backdoor recover one.

**Comment by prostreetprotege** [comment]
Oh!
My computer have a mulware attack
i'm Should buy a new ecu   T_T
