### ISSUE TITLE
Hondaecu 320 tes read CRF150L

### ISSUE THREAD

**Issue by edwinopie** [MCU-Innovations/HondaECU#55]
hi
try to read, i think its reading. i got 48kb bin file. but progress reading is not seen(the green bar)
[tes read flash crf150l 4000.txt](https://github.com/MCU-Innovations/HondaECU/files/3495437/tes.read.flash.crf150l.4000.txt)

[tes crf read hondaecu 4000.zip](https://github.com/MCU-Innovations/HondaECU/files/3495440/tes.crf.read.hondaecu.4000.zip)
start offset 4000

**Comment by RyanHope** [comment]
Try reading from 0x7000

**Comment by edwinopie** [comment]
ok. how is the bin size should be? more than 48kb?

**Comment by RyanHope** [comment]
im not sure on this ecu, I assume you tried reading from 0 and that failed?

**Comment by edwinopie** [comment]
Reading complete. But result is bad.. that written on small pop window.. i
forget to screenshot. Try again soon.. my kkl ft232rl is burning i guess..
i dont know why

**Comment by edwinopie** [comment]
Hi. Can i use any tipe FTDI chip for this? Or there ia a specific type of th FTDI?
