### ISSUE TITLE
Which USB FTDI Cable working good with Hondaecu?

### ISSUE THREAD

**Issue by edwinopie** [MCU-Innovations/HondaECU#56]
hi,
Kindly to share which cable working well with HondaECU?

**Comment by RyanHope** [comment]
I have not found a commercial cable that I like yet. I have tried the cheap VAG COM KKL clones on ebay, they work for a while then eventually burn out. I've had the best luck building the circuit that is on my github page. I am working a new solution that should be really cheap and available for the world wide market.

**Comment by edwinopie** [comment]
thats explain why my vag com kkl burn out too...

**Comment by edwinopie** [comment]
any specific FTDI type for hondaECU?

**Comment by RyanHope** [comment]
Real FTDI chips are more robust to poor signals than the clone chips are, but if the kline conversion part of the circuit is correct everything should work. In addition to the opamp circuit I also made a circuit with transistors that worked well. The opamps are very robust to electrical spikes and wont burn out like the opamps used in the vag com cables. I do however worry that the opamps are too slow and are causing issues with higher baud rates.

**Comment by edwinopie** [comment]
i found USB to Kline interface from europe, plan to order it and give it a try.. it is using original FTDI chip.

**Comment by edwinopie** [comment]
what is the protocol of the ecu? is it K-Line (ISO 9141)?

**Comment by RyanHope** [comment]
the protocol is proprietary

**Comment by edwinopie** [comment]
can i use this cable which has FTDI RS232 to USB adapter with an ST L9637 line driver?

**Comment by RyanHope** [comment]
if its a kline adapter with an ftdi chip it should work (tm)... thats all I can say

**Comment by edwinopie** [comment]
noted, thank you
