### ISSUE TITLE
Address to Start/Finish read

### ISSUE THREAD

**Issue by edwinopie** [MCU-Innovations/HondaECU#59]
wondering filling address as a start mark to read flash, is the HondaECU knows the address by itself where to finish read? because its related to the size of the bin file, or it detect atuomatically?

**Comment by RyanHope** [comment]
HondaECU stops reading when it stops receiving data in the responses. The only critical value seems to be the starting location.

**Comment by edwinopie** [comment]
noted, 

for an example :
CRF110F | 2019 | 64 kb | 38770-KYK-D12 | 0 | 8000 
the file size is 64kb, start read from 8000, it should be end read at 17FFF, right?

so if unknown ecu, unkown bin size? how to find out those info(bin size, start read address, finish read address)

**Comment by RyanHope** [comment]
There is no way to know 100% in advance. You can make some assumptions based on a comparison of its physical size and part number to other similar ECUs. You can just try reading at different offsets until you get a good read. You can cut into one and get the chip part number then lookup the memory layout in a data sheet.

**Comment by edwinopie** [comment]
thanks for the information, give me another view about reading scheme of HondaECU. 
On assumption side as you said, you mean similar part number, like 38770-xxx-901 is maybe identicall to 38770-yyy-901, can i assume that way?

**Comment by RyanHope** [comment]
No its the middle letters that matter. 38770 is Hondas part code for
ECU...the middle 3 letters identifies the ECU hardware and the last 3
is the region/software differences. With very few exceptions if the
middle 3 letters match, then the ECU is bin compat with other software
versions. That doesn't mean the bike will run as some regions are
missing sensors or have immobilizers, etc. But there also seem to be
other patterns, all the 38770-K??-??? ecus seem to be based on m16c
MCUS, the CB/CBR 600/1000's use m32r, the CRFs and newer mid sized
bikes (cbr500, cb650) all seem to use PPCs.

**Comment by edwinopie** [comment]
i see.. from what i found is different, the middle 3 numbers/letters is model code, i dont know maybe it depends on where market sales for that bike.. i know little about oem spec by market, i used to work as product development engineer in a car maker company..

**Comment by edwinopie** [comment]
if i compare those file (same end 3 digit) using hex editor or winols, clearly it seen that they are identical.. not 100% of course,,

**Comment by RyanHope** [comment]
yes the middle 3 roughly lines up with model code but the same ecus are used on CB and CBRs and those are clearly different models, what is the same is they run the same engine and thus use the same ecu hardware

**Comment by edwinopie** [comment]
please take a look..
![D01 cmpare](https://user-images.githubusercontent.com/52882543/63227693-51e3b700-c224-11e9-8823-1db348c8c0dc.jpg)

**Comment by RyanHope** [comment]
What are you trying to show/prove here?

**Comment by edwinopie** [comment]
a guide line for unknown ecu, in my opinion the last 3 digit is maybe the closest assumption to be a starting point. so i think it will be good to add a parameter to input last 3 digit (if the user has no clue about start read address) and connect to a known database to get a start reading address.. this is only an input for HondaECU to make it more adaptable to unknown ecu..

**Comment by RyanHope** [comment]
None of what you just said address my question about what you were trying to imply with that screenshot?

**Comment by edwinopie** [comment]
the screenshot shows it look identical, so i guess the start reading address could be the same because those files has the same last 3 digits.. i dont know, correct me if im wrong..

**Comment by RyanHope** [comment]
The start of those files all look the same cause the hardware is the same. And, all the examples you posted were from a similar year/generation so they were running the same OS version (i.e. same version of PGM-FI). The files are still very different if you look beyond the first few bytes in your screenshots... but those differences are all in maps and tables mostly.

**Comment by edwinopie** [comment]
noted..
