### ISSUE TITLE
38770-K56-M01

### ISSUE THREAD

**Issue by briantrepo** [MCU-Innovations/HondaECU#60]
Hai , does anyone here have the original RS150 38770-K56-M01 bin file.  please give it to me to fix it again.  thanks

**Comment by RyanHope** [comment]
The issue tracker is not a big request site...

**Comment by briantrepo** [comment]
I'm sorry, but I'm having a problem reading ecu but the results are bad,
and I want to get the best results.
 Once again, I'm sorry, thank you

Pada tanggal Sen, 19 Agt 2019 21:16, Ryan Hope <notifications@github.com>
menulis:

**Comment by RyanHope** [comment]
Thats probably because it is running a buggy version of PGM-FI and the read is corrupted. It has been mentioned many times in these threads that many/most of the new 38770-K**-*** ecus must be read from the backdoor to get a good read.

**Comment by briantrepo** [comment]
I would love to see a video of how you read through the back, so I know
it.  You can share it via Facebook or anywhere.  please make a video for me
and for others.  thank you.

Pada tanggal Sen, 19 Agt 2019 21:48, Ryan Hope <notifications@github.com>
menulis:

**Comment by RyanHope** [comment]
There are some tips about it on my facebook page. But basically, depot the ecu, find all the test pads, figure out the Tx/Rx/Vcc/Gnd pins, connect them to a ftdi breakout board and then use Renesas FDT to do the read.

**Comment by briantrepo** [comment]
Ok , i want to know when you start running the FDT application until it's
finished.
 Can you make it  I will wait for your video, that's all I want from you

Pada tanggal Sen, 19 Agt 2019 22:15, Ryan Hope <notifications@github.com>
menulis:

**Comment by RyanHope** [comment]
You are asking a lot of me man, this is a free project...

**Comment by briantrepo** [comment]
I'm sorry if you ask too many questions, sorry my friend just looking for a
solution.

Pada tanggal Sen, 19 Agt 2019 22:45, Ryan Hope <notifications@github.com>
menulis:

**Comment by RyanHope** [comment]
See #61
