### ISSUE TITLE
EEPROM Write/interrupted

### ISSUE THREAD

**Issue by prostreetprotege** [MCU-Innovations/HondaECU#62]
Hey Ryan
i'm test EEPROM Function on V3.3.0
Read is OK
Format is OK
Write is interrupted
Bike have a HISS Show and can't Start

Use V3.3.0 and D.I.Y Cable

**Comment by prostreetprotege** [comment]
![image](https://user-images.githubusercontent.com/53036434/63321776-e5fc6e00-c34b-11e9-8bec-6472090e2078.png)

**Comment by RyanHope** [comment]
Are you testing on the bench or on the bike? I have not been able to do
much testing with bikes that actually have HISS. Once of my regular testers
has noted some similar issues.

**Comment by prostreetprotege** [comment]
I test on the bike.
I delete hiss location in bin and flash to bike.
My bike can Start again

**Comment by uszzz** [comment]
Can you advice how to turn HISS off in bin? Thanks in advance.

**Comment by prostreetprotege** [comment]
I can't tell the position clearly.
Because each ecu is different
In cbr500, it's around the ecmid

**Comment by uszzz** [comment]
Then what byte(s) to look for?

**Comment by prostreetprotege** [comment]
You must find ecmid location first.
And hiss is about 2 lines before ecmid

**Comment by RyanHope** [comment]
not on all ecus

**Comment by elmikel147** [comment]
good morning to all of you. what does ecmid mean? thanks to this wonderful forum.
